# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_option', models.IntegerField(default=-1)),
                ('hint', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='contests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_name', models.CharField(max_length=300)),
                ('is_rated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='scoring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('is_verified', models.BooleanField(default=False)),
                ('profile_pic', models.CharField(default='NIL', max_length=1000)),
                ('number_of_contests', models.IntegerField(default=-1)),
            ],
        ),
    ]
