# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='profile_pic',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
