# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 13:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171021_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='contests',
            name='date',
            field=models.DateField(default=datetime.date(2017, 10, 21)),
        ),
        migrations.AddField(
            model_name='contests',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 13, 22, 9, 39095, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contests',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 13, 22, 9, 39064, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='contests',
            name='total_score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='contests',
            name='type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='questions',
            name='contest_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='questions',
            name='question_type',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='scoring',
            name='contest_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='scoring',
            name='score_secured',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='scoring',
            name='total_score',
            field=models.FloatField(default=-1.0),
        ),
        migrations.AddField(
            model_name='scoring',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
