# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171021_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contests',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 10, 21, 13, 23, 20, 268679, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contests',
            name='end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 13, 23, 20, 268764, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contests',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 21, 13, 23, 20, 268737, tzinfo=utc)),
        ),
    ]
