# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-21 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171021_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_file', models.FileField(null=True, upload_to='')),
                ('output_file', models.FileField(null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='question_type',
        ),
        migrations.AddField(
            model_name='questions',
            name='constraints',
            field=models.CharField(default='NA', max_length=2000),
        ),
        migrations.AddField(
            model_name='questions',
            name='description',
            field=models.CharField(default='NA', max_length=20000),
        ),
        migrations.AddField(
            model_name='questions',
            name='editorial',
            field=models.CharField(default='WA', max_length=40000),
        ),
        migrations.AddField(
            model_name='questions',
            name='sample_testcases',
            field=models.CharField(default='NA', max_length=20000),
        ),
        migrations.AlterField(
            model_name='contests',
            name='type',
            field=models.CharField(choices=[('MCQ', 'MCQ'), ('Coding', 'Coding')], max_length=100),
        ),
    ]
