# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171021_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='editor_language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('language_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='editor_themes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=100)),
                ('theme_id', models.CharField(max_length=100)),
            ],
        ),
    ]
