# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_editor_language_editor_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor_language',
            name='sample_code',
            field=models.TextField(default='NA', max_length=100000),
            preserve_default=False,
        ),
    ]
